{% set name = "pycppad" %}
{% set version = "1.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Simple-Robotics/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 91a67a1bc2d491546bb4df243cb20f2e2c8bb4d6062d8a2ec9c89f0643dc2817

build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - vs2017_win-64  # [win64]
    - vs2017_win-32  # [win32]
    - cmake
    - make  # [not win]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
  host:
    - eigen
    - boost
    - python
    - cppad
    - cppadcodegen  # [not win]
    - eigenpy
    - numpy  # [build_platform != target_platform]
  run:
    - eigen
    - boost
    - python
    - cppad
    - cppadcodegen  # [not win]
    - eigenpy
    - {{ pin_compatible('numpy') }}  # [build_platform != target_platform]

test:
  requires:
    - pkg-config
  imports:
    - pycppad
  commands:
    - pkg-config --modversion pycppad

about:
  home: http://github.com/Simple-Robotics/pycppad
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python bindings for CppAD and CppADCodeGen using Boost.Python
  dev_url: http://github.com/Simple-Robotics/pycppad

extra:
  recipe-maintainers:
    - proyan
    - jcarpent
